version: '3.8'
services:
  tomcat-java:
    build: ./java
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./java/src:/usr/local/tomcat/webapps:cached
    depends_on:
      - mariadb

  # MariaDB
  mariadb:
    build: ./mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ../data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sample_root_passward
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_pass