version: '3.8'
services:
  tomcat-java:
    build: #構築時に適用するオプション
      context: ./java
      dockerfile: Dockerfile
    working_dir: /srv #作業ディレクトリの指定
    ports: #ホスト側:コンテナ側 でポートを指定
      - 8080:8080
    tty: true #コンテナが正常終了せず、起動したままになる
    volumes: #ローカルファイルをDockerコンテナ内にマウントし、データを永続化する
      #[ソース:]ターゲット[:モード]
      - ./java:/srv:cached

  # MariaDB
  mariadb:
    build: ./mariadb
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ../data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sample_root_passward
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_pass